### ISSUE TITLE
Portage sur homebridge

### ISSUE THREAD

**Issue by fastenspy** [henribi/jeedom-plugin-mczremote#1]
Bonjour henribi, j'ai vu ton post sur le forum de jeedom community. Pense-tu que c'est possible de faire tourner ton plugin sur homebridge (Rpi) ?

Merci d'avance

**Comment by henribi** [comment]
Bonjour,  Non, je ne pense pas.  Le plugin nécessite Jeedom pour démarrer.  Par contre, tu as le script python seul disponible en https://github.com/henribi/Maestro_Remote.   Il dialogue avec le poêle via les serveurs de MCZ d'un côté et de l'autre via MQTT.  Il y publie les infos du poêle dans un topic PUBmcz et reçoit les commandes pour le poêle via le topic SUBmcz.   Je suppose que homebridge peu dialoguer avec MQTT.
